from typing import Dict, Any

TEXTS = {
    "ru": {
        "welcome": "Добро пожаловать в МедНапоминалку! Я буду помогать вам не забывать принимать лекарства вовремя.",
        "language_selected": "Вы выбрали русский язык.",
        "select_language": "Выберите язык / Select language:",
        "main_menu": "Главное меню:",
        "add_pill": "Добавить лекарство",
        "today_pills": "Лекарства на сегодня",
        "settings": "Настройки",
        "subscription": "Подписка",
        "enter_pill_name": "Введите название лекарства:",
        "select_schedule": "Выберите режим приёма:",
        "morning": "Утро",
        "day": "День",
        "evening": "Вечер",
        "custom_time": "Своё время",
        "select_time": "Выберите время приёма:",
        "enter_custom_time": "Введите своё время в формате ЧЧ:ММ (например, 08:30):",
        "invalid_time_format": "Неверный формат времени. Пожалуйста, используйте формат ЧЧ:ММ (например, 08:30).",
        "pill_added": "Лекарство {name} добавлено на {time}",
        "no_pills_today": "На сегодня нет запланированных лекарств.",
        "today_checklist": "Ваш чек-лист на сегодня ({date}):",
        "morning_pills": "🌅 Утро:",
        "day_pills": "☀️ День:",
        "evening_pills": "🌙 Вечер:",
        "pill_item": "{name} - {time}",
        "mark_as_taken": "✅ Принято",
        "marked_as_taken": "Отмечено как принято: {name}",
        "reminder": "Напоминание: Пора принять {name}!",
        "reminder_repeat": "Напоминаю: Вы ещё не отметили приём лекарства {name}!",
        "subscription_info": "Информация о подписке:",
        "free_plan": "У вас бесплатный план. Реклама отображается в напоминаниях.",
        "premium_plan": "У вас премиум-подписка до {date}.",
        "lifetime_plan": "У вас бессрочная премиум-подписка.",
        "subscription_plans": "Планы подписки:",
        "monthly_plan": "Месячная - 99₽",
        "yearly_plan": "Годовая - 799₽",
        "lifetime_plan_purchase": "Бессрочная - 1999₽",
        "subscription_expiring": "Ваша подписка истекает завтра. Желаете продлить?",
        "subscription_expired": "Ваша подписка истекла. Теперь вы используете бесплатный план с рекламой.",
        "payment_success": "Оплата прошла успешно! Ваша подписка активирована.",
        "payment_failed": "Произошла ошибка при оплате. Пожалуйста, попробуйте снова позже.",
        "admin_welcome": "Панель администратора. Выберите действие:",
        "admin_stats": "Статистика",
        "admin_users": "Управление пользователями",
        "admin_logs": "Логи и отчёты",
        "admin_stats_info": "Статистика бота:\n\nВсего пользователей: {total_users}\nАктивных пользователей (7 дней): {active_users}\nПремиум-пользователей: {premium_users}\nСреднее количество лекарств на пользователя: {avg_pills}\nДоход за месяц: {monthly_income}₽",
        "admin_ban_success": "Пользователь {user_id} заблокирован.",
        "admin_unban_success": "Пользователь {user_id} разблокирован.",
        "admin_extend_success": "Подписка пользователя {user_id} продлена на {days} дней.",
        "user_blocked": "Вы были заблокированы администратором. Обратитесь в поддержку для выяснения причин.",
        # "ad_banner": "🔍 Попробуйте новое приложение для отслеживания здоровья! Скачайте сейчас: health-app.com",
        "my_medications": "Мои лекарства",
        "your_medications": "Ваши лекарства:",
        "no_medications": "Вы еще не добавили ни одного лекарства.",
        "custom_pills": "🕒 Своё время:",
        "manage_medications": "Что вы хотите сделать?",
        "delete_medication": "Удалить лекарство",
        "select_medication_to_delete": "Выберите лекарство для удаления:",
        "cancel": "Отмена",
        "deletion_cancelled": "Операция отменена.",
        "medication_not_found": "Лекарство не найдено.",
        "confirm_delete_medication": "Вы уверены, что хотите удалить {name}?",
        "confirm_delete": "Да, удалить",
        "medication_deleted": "Лекарство {name} удалено.",
        "reminder_settings": "Настройки напоминаний",
        "reminders_enabled": "Напоминания включены",
        "reminders_disabled": "Напоминания отключены",
        "enable_reminders": "Включить напоминания",
        "disable_reminders": "Отключить напоминания",
        "reminder_repeat_time": "Повторять напоминание через:",
        "5_minutes": "5 минут",
        "15_minutes": "15 минут",
        "30_minutes": "30 минут",
        "reminder_settings_updated": "Настройки напоминаний обновлены",
        "take_now": "Принять сейчас",
        "snooze": "Отложить",
        "disable_this_reminder": "Отключить это напоминание",
        "reminder_disabled": "Напоминание отключено",
        "snoozed_for": "Напоминание отложено на {minutes} минут",
        "change_language": "Сменить язык",
        "limit_reached": "Вы не можете добавить более 5 лекарств. Перейдите на Premium для снятия ограничений.",
        "premium_status_active": "🌟 Ваш Premium активен до {expiry_date}",
        "premium_status_inactive": "🔒 Premium неактивен",
        "trial_activated": "🎁 Вы активировали 30-дневный пробный период Premium!",
    },
    "en": {
        "welcome": "Welcome to MedReminder! I will help you remember to take your medications on time.",
        "language_selected": "You have selected English language.",
        "select_language": "Select language / Выберите язык:",
        "main_menu": "Main menu:",
        "add_pill": "Add medication",
        "today_pills": "Today's medications",
        "settings": "Settings",
        "subscription": "Subscription",
        "enter_pill_name": "Enter the medication name:",
        "select_schedule": "Select intake schedule:",
        "morning": "Morning",
        "day": "Day",
        "evening": "Evening",
        "custom_time": "Custom time",
        "select_time": "Select intake time:",
        "enter_custom_time": "Enter your custom time in HH:MM format (e.g., 08:30):",
        "invalid_time_format": "Invalid time format. Please use HH:MM format (e.g., 08:30).",
        "pill_added": "Medication {name} added at {time}",
        "no_pills_today": "No medications scheduled for today.",
        "today_checklist": "Your checklist for today ({date}):",
        "morning_pills": "🌅 Morning:",
        "day_pills": "☀️ Day:",
        "evening_pills": "🌙 Evening:",
        "pill_item": "{name} - {time}",
        "mark_as_taken": "✅ Taken",
        "marked_as_taken": "Marked as taken: {name}",
        "reminder": "Reminder: Time to take {name}!",
        "reminder_repeat": "Reminder: You haven't marked {name} as taken yet!",
        "subscription_info": "Subscription information:",
        "free_plan": "You have a free plan. Ads are shown in reminders.",
        "premium_plan": "You have a premium subscription until {date}.",
        "lifetime_plan": "You have a lifetime premium subscription.",
        "subscription_plans": "Subscription plans:",
        "monthly_plan": "Monthly - $1.99",
        "yearly_plan": "Yearly - $9.99",
        "lifetime_plan_purchase": "Lifetime - $24.99",
        "subscription_expiring": "Your subscription expires tomorrow. Would you like to renew?",
        "subscription_expired": "Your subscription has expired. You are now using the free plan with ads.",
        "payment_success": "Payment successful! Your subscription has been activated.",
        "payment_failed": "Payment failed. Please try again later.",
        "admin_welcome": "Admin panel. Choose an action:",
        "admin_stats": "Statistics",
        "admin_users": "User management",
        "admin_logs": "Logs and reports",
        "admin_stats_info": "Bot statistics:\n\nTotal users: {total_users}\nActive users (7 days): {active_users}\nPremium users: {premium_users}\nAverage medications per user: {avg_pills}\nMonthly income: ${monthly_income}",
        "admin_ban_success": "User {user_id} has been banned.",
        "admin_unban_success": "User {user_id} has been unbanned.",
        "admin_extend_success": "User {user_id} subscription extended by {days} days.",
        "user_blocked": "You have been blocked by the administrator. Please contact support for more information.",
        # "ad_banner": "🔍 Try the new health tracking app! Download now: health-app.com",
        "my_medications": "My medications",
        "your_medications": "Your medications:",
        "no_medications": "You haven't added any medications yet.",
        "custom_pills": "🕒 Custom time:",
        "manage_medications": "What would you like to do?",
        "delete_medication": "Delete medication",
        "select_medication_to_delete": "Select medication to delete:",
        "cancel": "Cancel",
        "deletion_cancelled": "Operation cancelled.",
        "medication_not_found": "Medication not found.",
        "confirm_delete_medication": "Are you sure you want to delete {name}?",
        "confirm_delete": "Yes, delete",
        "medication_deleted": "Medication {name} has been deleted.",
        "reminder_settings": "Reminder Settings",
        "reminders_enabled": "Reminders are enabled",
        "reminders_disabled": "Reminders are disabled",
        "enable_reminders": "Enable reminders",
        "disable_reminders": "Disable reminders",
        "reminder_repeat_time": "Repeat reminder after:",
        "5_minutes": "5 minutes",
        "15_minutes": "15 minutes",
        "30_minutes": "30 minutes",
        "reminder_settings_updated": "Reminder settings updated",
        "take_now": "Take now",
        "snooze": "Snooze",
        "disable_this_reminder": "Disable this reminder",
        "reminder_disabled": "Reminder disabled",
        "snoozed_for": "Reminder snoozed for {minutes} minutes",
        "change_language": "Change language",
        "limit_reached": "You can't add more than 5 medications. Upgrade to Premium for unlimited access.",
        "premium_status_active": "🌟 Ваш Premium активен до {expiry_date}",
        "premium_status_inactive": "🔒 Premium неактивен",
        "trial_activated": "🎁 Вы активировали 30-дневный пробный период Premium!",
    }
}

def get_text(key: str, language: str, **kwargs: Any) -> str:
    """Get localized text by key and language with optional formatting"""
    language = language if language in TEXTS else "en"
    text = TEXTS[language].get(key, TEXTS["en"].get(key, f"Missing text for: {key}"))
    if kwargs:
        return text.format(**kwargs)
    return text
